//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractorAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContractorAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractorDB.db.
        /// </summary>
        internal static string ContractorDB {
            get {
                return ResourceManager.GetString("ContractorDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contractors.
        /// </summary>
        internal static string Contractors {
            get {
                return ResourceManager.GetString("Contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6d8c7cc8a95ea6fb36302090bff101d914f0aa6d.
        /// </summary>
        internal static string DaDataToken {
            get {
                return ResourceManager.GetString("DaDataToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контрагент не существует в ЕГРЮЛ.
        /// </summary>
        internal static string NotExistsInEGRUL {
            get {
                return ResourceManager.GetString("NotExistsInEGRUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контрагент не валидный. Проверьте данные..
        /// </summary>
        internal static string NotValidContractorMessage {
            get {
                return ResourceManager.GetString("NotValidContractorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string NumberOfExampleRowsToAdd {
            get {
                return ResourceManager.GetString("NumberOfExampleRowsToAdd", resourceCulture);
            }
        }
    }
}
